- config/repositories.yml
See: https://mlit.slack.com/archives/C6EEQ9135/p1673028828422949
> Configure bhl production url

- app/assets/stylesheets/umich-arclight/_help.scss
- app/assets/stylesheets/umich-arclight/index.scss
- app/controllers/help_controller.rb
- app/views/arclight/help.html.erb
- app/views/shared/_footer.html.erb
- config/routes.rb
- adds a `help` route
- adds a `help` template
- adds some `help` styles
> DCP2-433 - add help page

- config/locales/dul_arclight.en.yml
- config/locales/um_arclight.en.yml
Changes "See all containers" to "Expand list" to resolve [DCP2-418](https://mlit.atlassian.net/browse/DCP2-418) and [DCP2-402](https://mlit.atlassian.net/browse/DCP2-402).
[Current link](https://staging.arclight.kubernetes.lib.umich.edu/catalog/umich-bhl-0420_aspace_9b1a88e07eeef6abb22ac47db9067c39)
[Local link](http://localhost:3000/catalog/umich-bhl-0420_aspace_9b1a88e07eeef6abb22ac47db9067c39)
[DCP2-418]: https://mlit.atlassian.net/browse/DCP2-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCP2-402]: https://mlit.atlassian.net/browse/DCP2-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCP2-418 DCP2-402 Change see all containers to Expand list

- .docker/branch.dockerfile
- .github/workflows/build-branch-image.yml
> build branch image

- .rubocop_todo.yml
- app/helpers/dul_arclight_helper.rb
> Resolves DCP2-467: ArcLight - enable full breadcrumb list (option 2)

- app/assets/javascripts/arclight/collection_navigation.js
- app/assets/stylesheets/umich-arclight/_base.scss
- app/assets/stylesheets/umich-arclight/_collections.scss
- app/assets/stylesheets/umich-arclight/_utilities.scss
- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
- app/views/catalog/_containers.html.erb
- app/views/catalog/_index_child_components_nestable.html.erb
- config/environments/development.rb
To help keep context while users explore the collection:
> DCP2-481 - make contents expandable

- .github/workflows/zbuild-app-image.yml
- .github/workflows/zbuild-db-image.yml
- .github/workflows/zbuild-rails-image.yml
- .github/workflows/zbuild-redis-image.yml
- .github/workflows/zbuild-resque-image.yml
- .github/workflows/zbuild-resque-web-image.yml
- .github/workflows/zbuild-solr-image.yml
> retitle workflows

- app/assets/stylesheets/umich-arclight/_collections.scss
- app/assets/stylesheets/umich-arclight/_utilities.scss
- app/views/catalog/_containers.html.erb
- app/views/catalog/_index_child_components_nestable.html.erb
In the components list: remove zebra striping; add borders; hide bullets
> Lose the roundels

- app/jobs/package_finding_aid_job.rb
- app/models/concerns/dul_arclight/solr_document.rb
- app/views/arclight/fragments/_component_details.html.erb
- app/views/arclight/fragments/_utility_styles.html.erb
- app/views/catalog/_show_default.html.erb
- lib/tasks/generate.rake
- lib/um_arclight/package/generator.rb
- spec/lib/um_arclight/package/generator_spec.rb
* split html and pdf steps
* download all stylesheet (and fonts and images) locally before building PDFs
* deal with component-less EADs
> rotareneG egakcaP etadpU

- app/models/concerns/dul_arclight/catalog.rb
Update `catalog.rb` to pull in the download helper.
> explicltly require download helper

- lib/tasks/solr.rake
Handy dandy tasks for Solr Cloud Collection CRUD
> Solr Cloud Configuration Sets and Collections Rake Tasks

- public/robots.txt
* add link to sitemap URL
* add derivatives to `Disallow` directives
> DCP2-534 update robots.txt

- app/controllers/catalog_controller.rb
- lib/dul_arclight/traject/ead2_config.rb
- solr/arclight/conf/schema.xml
- solr/arclight/conf/solrconfig.xml
> Resolves DCP2-531: ArcLight - add creator credits at end of summary

- lib/um_arclight/package/generator.rb
* use `Dir.chdir do ... end` to avoid leaving the generator in the wrong directory
* request all fields, like we're doing when presenting the component tree
> DCP2-491 - use the block form of Dir.chdir

- lib/dul_arclight/normalized_date.rb
- spec/lib/dul_arclight/normalized_date_spec.rb
yet again!  Removes leading comma.
> Resolves ARC-29: Make bulk "Majority within" statement more concise

- config/locales/um_arclight.en.yml
Ugh! Too many locales files!!!
> Resolves ARC-83: Minor text change for linked digital archival objects

- app/views/catalog/_arclight_index_default.html.erb
- app/views/catalog/_index_child_components_default.html.erb
- app/views/catalog/_index_child_components_nestable.html.erb
> Resolves ARC-93: Add context separator to search results snippets.

- app/views/findingaids/_attributes.erb
Display error only on show page.
> Resolves ARC-94 findingaids index view crash on error.

- Gemfile
- Gemfile.lock
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/deprecation.rb
- docker-compose.yml
Add Semantic Logger
Turn off Blacklight search history tracking
Silence Blacklight deprecation warnings
Set RAILS_LOG_TO_STDOUT to true in docker-compose.yml
> Resolves ARC-96 Semantic Logger

- app/views/catalog/_aeon_request_checkbox.html.erb
- app/views/catalog/_show_default.html.erb
Render request button on child page.
> ARC-78 Hot Fix

- app/views/catalog/_show_default.html.erb
> request button flag

- app/views/catalog/_show_default.html.erb
Move upper metadata above contents div.
> ARC-90 Hot Fix

- app/assets/stylesheets/application.scss
- app/helpers/um_arclight_helper.rb
- app/models/solr_document.rb
and add odds and notes to abstract_or_scope
> Remove note and odd from interesting children

- config/repositories.yml
Clements added links to the Gage finding aid so we need to add gage to the list for embeds
> Adding gage for embed

- lib/dul_arclight/traject/ead2_config.rb
- solr/arclight/conf/schema.xml
ARC-106 Contents of Additional Descriptive Data not turning up in searches.
> Copy add_teim field to text field (Additional Descriptive Data)

- app/controllers/findingaids_controller.rb
- data/ead2002/dtd2schema.xsl
Added the display of transformed EAD XML document in the error message.
> ARC-113-Error-XML-schema-validate
